// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnSteerCancelParams = { threadId: string,
/**
 * Pending user messages to remove. Core returns the subset that was still
 * pending; already-consumed messages are omitted.
 */
clientUserMessageIds: Array<string>,
/**
 * Required active turn id precondition. The request fails when it does not
 * match the currently active turn.
 */
expectedTurnId: string, };
