// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowAgentActivity } from "./WorkflowAgentActivity";
import type { WorkflowAgentState } from "./WorkflowAgentState";
import type { WorkflowIsolation } from "./WorkflowIsolation";

export type WorkflowAgentProgress = {
/**
 * Stable invocation identity within one workflow definition.
 */
invocationId: string, index: number, label: string, phaseIndex: number | null, phaseTitle: string | null, agentId: string | null, model: string | null, fallbackModel: string | null, isolation: WorkflowIsolation | null, state: WorkflowAgentState, activity: WorkflowAgentActivity | null, blocked: boolean, skipped: boolean,
/**
 * True while the workflow waits for the user to retry or skip this agent.
 */
awaitingDecision: boolean, cached: boolean, attempt: number, error: string | null, tokens: bigint | null, toolCalls: bigint | null, durationMs: bigint | null, resultPreview: string | null, promptPreview: string,
/**
 * Unix timestamp in seconds when the call entered the workflow queue.
 */
queuedAt: bigint,
/**
 * Unix timestamp in seconds when agent execution began.
 */
startedAt: bigint | null,
/**
 * Unix timestamp in seconds when this progress item was last updated.
 */
lastProgressAt: bigint, };
