// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowProgressItem } from "./WorkflowProgressItem";
import type { WorkflowUsage } from "./WorkflowUsage";

export type WorkflowProgressNotification = { threadId: string, turnId: string, taskId: string, runId: string, progress: Array<WorkflowProgressItem>, usage: WorkflowUsage, };
