// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";

export type WorkflowStartedNotification = { threadId: string, turnId: string, taskId: string, runId: string, workflowName: string, title: string | null, summary: string, transcriptDir: LegacyAppPathString, scriptPath: LegacyAppPathString,
/**
 * Stable identity for deduplicating online delivery retries.
 */
deliveryKey: string, startedAt: bigint, };
