// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowAgentProgress } from "./WorkflowAgentProgress";
import type { WorkflowProgressKind } from "./WorkflowProgressKind";

export type WorkflowProgressItem = { "type": "workflowPhase", index: number, title: string, kind: WorkflowProgressKind, } | { "type": "workflowAgent" } & WorkflowAgentProgress | { "type": "workflowLog", message: string, };
