// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { WorkflowStatus } from "./WorkflowStatus";
import type { WorkflowUsage } from "./WorkflowUsage";

export type WorkflowCompletedNotification = { threadId: string, turnId: string, taskId: string, runId: string, workflowName: string, status: WorkflowStatus, summary: string,
/**
 * Path to the persisted run snapshot, including the terminal result.
 */
outputFile: LegacyAppPathString, error: string | null, failures: Array<string>, usage: WorkflowUsage,
/**
 * Stable identity for deduplicating online delivery retries.
 */
deliveryKey: string,
/**
 * Indicates that clients should refresh progress from the persisted task.
 */
progressResyncRequired: boolean, completedAt: bigint, };
