// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowUsage = { totalTokens: bigint, toolUses: bigint, durationMs: bigint, agentCount: number, successfulAgentCount: number, failedAgentCount: number, skippedAgentCount: number, nullAgentResultCount: number, };
