// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { WorkflowProgressItem } from "./WorkflowProgressItem";
import type { WorkflowStatus } from "./WorkflowStatus";
import type { WorkflowUsage } from "./WorkflowUsage";

export type WorkflowTask = { threadId: string, turnId: string, taskId: string, runId: string, workflowName: string, title: string | null, status: WorkflowStatus, summary: string, transcriptDir: LegacyAppPathString, scriptPath: LegacyAppPathString,
/**
 * Path to the persisted run snapshot, including terminal result metadata.
 */
outputFile: LegacyAppPathString, progress: Array<WorkflowProgressItem>, progressVersion: bigint, usage: WorkflowUsage, failures: Array<string>, error: string | null, startedAt: bigint, completedAt: bigint | null, };
