//! Deterministic JavaScript workflows that orchestrate Codex subagents.

pub const WORKFLOW_AGENT_PROMPT_SEPARATOR: &str = "\n\n";
pub const WORKFLOW_SUBAGENT_PREAMBLE: &str = r#"You are a workflow subagent. Complete the task below thoroughly and return its result as your final response. Your final response is returned as a value to the owning workflow. Work independently with the available tools and preserve exact evidence such as paths, line numbers, URLs, commands, and errors."#;

mod child;
mod inputs;
mod model;
mod result;
mod runtime;
mod scope_analysis;
mod script;

pub use child::WorkflowChildReference;
pub use inputs::MemoryWorkflowInputArtifactStore;
pub use inputs::ResolvedWorkflowInputs;
pub use inputs::WorkflowAgentInputs;
pub use inputs::WorkflowInputArtifactFuture;
pub use inputs::WorkflowInputArtifactKind;
pub use inputs::WorkflowInputArtifactLocation;
pub use inputs::WorkflowInputArtifactRef;
pub use inputs::WorkflowInputArtifactStore;
pub use inputs::WorkflowInputDescriptor;
pub use inputs::WorkflowInputPathSegment;
pub use inputs::canonical_workflow_input_bytes;
pub use inputs::store_workflow_input_descriptor;
pub use inputs::validate_artifact_sha256;
pub use inputs::validate_v8_lossless_json_numbers;
pub use inputs::workflow_input_artifact_ref;
pub use inputs::workflow_input_descriptor_ref;
pub use model::MAX_WORKFLOW_AGENT_STALL_MS;
pub use model::MAX_WORKFLOW_PROGRESS_TEXT_BYTES;
pub use model::WorkflowAgentActivity;
pub use model::WorkflowAgentFailure;
pub use model::WorkflowAgentFailureKind;
pub use model::WorkflowAgentOptions;
pub use model::WorkflowAgentOutcome;
pub use model::WorkflowAgentProgress;
pub use model::WorkflowAgentProgressUpdate;
pub use model::WorkflowAgentRequest;
pub use model::WorkflowAgentResult;
pub use model::WorkflowAgentState;
pub use model::WorkflowDeclaredInputFile;
pub use model::WorkflowDeclaredInputs;
pub use model::WorkflowEffort;
pub use model::WorkflowEvent;
pub use model::WorkflowExecutionError;
pub use model::WorkflowIsolation;
pub use model::WorkflowJournalResult;
pub use model::WorkflowMeta;
pub use model::WorkflowPhase;
pub use model::WorkflowProgressKind;
pub use model::WorkflowRunOutcome;
pub use model::WorkflowTokenUsage;
pub use result::MAX_WORKFLOW_RESULT_DEPTH;
pub use result::WorkflowResultLimitError;
pub use result::serialize_workflow_result;
pub use runtime::ResolvedWorkflowChild;
pub use runtime::WorkflowAgentFuture;
pub use runtime::WorkflowAgentProgressCallback;
pub use runtime::WorkflowAgentProgressFuture;
pub use runtime::WorkflowAgentRuntime;
pub use runtime::WorkflowAgentStartedCallback;
pub use runtime::WorkflowChildFuture;
pub use runtime::WorkflowChildRequest;
pub use runtime::WorkflowChildResolver;
pub use runtime::WorkflowControl;
pub use runtime::WorkflowEventSink;
pub use runtime::WorkflowEventSinkFuture;
pub use runtime::WorkflowJournal;
pub use runtime::WorkflowJournalFuture;
pub use runtime::WorkflowJournalReplayFuture;
pub use runtime::WorkflowRuntimeConfig;
pub use runtime::execute_workflow;
pub use script::MAX_WORKFLOW_SCRIPT_BYTES;
pub use script::ValidatedWorkflowScript;
pub use script::WorkflowScriptError;
pub use script::compile_workflow_source;
pub use script::validate_workflow_script;
