// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls whether the model should only spawn sub-agents after an explicit
 * user request or may delegate proactively when doing so would help.
 */
export type MultiAgentMode = "explicitRequestOnly" | "proactive";
