// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowResultReadStatus } from "./WorkflowResultReadStatus";

/**
 * Display item emitted while the owning model reads a Workflow result.
 */
export type WorkflowResultReadItem = { id: string, runId: string | null, status: WorkflowResultReadStatus, };
