// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display item emitted while a Workflow agent analyzes its injected inputs.
 */
export type WorkflowInputAnalysisItem = { id: string, };
